-- Seed « Sauve un arbre » — données fictives issues de Sauve_un_arbre_Budget_GrandLivre.xlsx
-- Généré automatiquement. À lancer après les migrations 0001..0022 sur une base fraîche.
begin;

-- Bailleurs
insert into bailleurs (code, name, color) values
  ('UE','Union europeenne','#003399'),
  ('FP','Fonds propres','#6b7280'),
  ('BAD','Banque africaine de developpement','#16a34a');

-- Structure budgetaire (niveau xlsx 0/1/2 -> level 1/2/3)
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1',1,'Frais generaux',null,10);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1',2,'Salaires',(select id from structure_lines where code='1'),20);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1.1',3,'Directeur',(select id from structure_lines where code='1.1'),30);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1.2',3,'Responsable financier',(select id from structure_lines where code='1.1'),40);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1.3',3,'Charge de programme',(select id from structure_lines where code='1.1'),50);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1.4',3,'Responsable communication',(select id from structure_lines where code='1.1'),60);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.1.5',3,'Formateurs (x2)',(select id from structure_lines where code='1.1'),70);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.2',2,'Bureaux',(select id from structure_lines where code='1'),80);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.2.1',3,'Loyer',(select id from structure_lines where code='1.2'),90);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.2.2',3,'Charges (eau/electricite/internet)',(select id from structure_lines where code='1.2'),100);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.3',2,'Frais administratifs',(select id from structure_lines where code='1'),110);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.3.1',3,'Fournitures de bureau',(select id from structure_lines where code='1.3'),120);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('1.3.2',3,'Audit / comptabilite',(select id from structure_lines where code='1.3'),130);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2',1,'Projets',null,140);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.1',2,'Projet A - Festival dans les ecoles (2024)',(select id from structure_lines where code='2'),150);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.1.1',3,'Frais d''animation festival',(select id from structure_lines where code='2.1'),160);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.1.2',3,'Materiel pedagogique',(select id from structure_lines where code='2.1'),170);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.1.3',3,'Deplacements / missions',(select id from structure_lines where code='2.1'),180);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.1.4',3,'Communication',(select id from structure_lines where code='2.1'),190);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2',2,'Projet B - Sensibilisation lyceens Cameroun/Congo/RCA (2025-2026)',(select id from structure_lines where code='2'),200);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2.1',3,'Formateurs terrain',(select id from structure_lines where code='2.2'),210);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2.2',3,'Deplacements / missions',(select id from structure_lines where code='2.2'),220);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2.3',3,'Materiel pedagogique',(select id from structure_lines where code='2.2'),230);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2.4',3,'Location de salles',(select id from structure_lines where code='2.2'),240);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.2.5',3,'Suivi-evaluation',(select id from structure_lines where code='2.2'),250);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3',2,'Projet C - MOOC protection des forets (2026)',(select id from structure_lines where code='2'),260);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3.1',3,'Developpement plateforme MOOC',(select id from structure_lines where code='2.3'),270);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3.2',3,'Production de contenus (video/cours)',(select id from structure_lines where code='2.3'),280);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3.3',3,'Hebergement / technique',(select id from structure_lines where code='2.3'),290);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3.4',3,'Communication / diffusion',(select id from structure_lines where code='2.3'),300);
insert into structure_lines (code, level, label, parent_id, sort_order) values ('2.3.5',3,'Coordination pedagogique',(select id from structure_lines where code='2.3'),310);

-- Budget previsionnel
insert into budgets (name, type, is_active, initial_cash) values ('Sauve un arbre - Previsionnel','interne',true,0);
insert into budget_years (budget_id, year) select id, y from budgets, (values (2024),(2025),(2026)) as t(y) where name='Sauve un arbre - Previsionnel';
-- budget_monthly : montant total de ligne place sur 1 mois distinct par bailleur (annee = annee projet)
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2024, 1, 8000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.1' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2024, 1, 5000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.2' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2024, 1, 4000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.3' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2024, 1, 3000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.4' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 1, 9000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.1' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 2, 9000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.1' and ba.code='FP';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 1, 6000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.2' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 2, 6000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.2' and ba.code='FP';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 1, 4000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.3' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 2, 4000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.3' and ba.code='FP';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 1, 3500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.4' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 2, 3500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.4' and ba.code='FP';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 1, 2500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.5' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2025, 2, 2500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.5' and ba.code='FP';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 1, 20000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.1' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 3, 20000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.1' and ba.code='BAD';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 1, 22500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.2' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 3, 22500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.2' and ba.code='BAD';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 1, 5000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.3' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 3, 5000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.3' and ba.code='BAD';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 1, 7500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.4' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 3, 7500, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.4' and ba.code='BAD';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 1, 5000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.5' and ba.code='UE';
insert into budget_monthly (budget_id, line_id, year, month, amount, bailleur_id) select b.id, sl.id, 2026, 3, 5000, ba.id from budgets b, structure_lines sl, bailleurs ba where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.5' and ba.code='BAD';
-- budget_line_totals : total annuel saisi (somme des bailleurs)
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2024, 8000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.1';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2024, 5000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.2';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2024, 4000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.3';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2024, 3000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.1.4';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2025, 18000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.1';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2025, 12000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.2';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2025, 8000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.3';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2025, 7000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.4';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2025, 5000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.2.5';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2026, 40000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.1';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2026, 45000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.2';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2026, 10000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.3';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2026, 15000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.4';
insert into budget_line_totals (budget_id, line_id, year, total_input) select b.id, sl.id, 2026, 10000 from budgets b, structure_lines sl where b.name='Sauve un arbre - Previsionnel' and sl.code='2.3.5';

-- Grand livre des depenses
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-03-15','Dépense','Frais d''animation festival',8000, sl.id, ba.id, '{"n_piece": "PC0001", "projet": "Projet A", "code": "2.1.1", "commentaire": "Realisation festival ecoles 2024 - solde 100%"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.1.1' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-04-20','Dépense','Materiel pedagogique',5000, sl.id, ba.id, '{"n_piece": "PC0002", "projet": "Projet A", "code": "2.1.2", "commentaire": "Realisation festival ecoles 2024 - solde 100%"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.1.2' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-06-10','Dépense','Deplacements / missions',4000, sl.id, ba.id, '{"n_piece": "PC0003", "projet": "Projet A", "code": "2.1.3", "commentaire": "Realisation festival ecoles 2024 - solde 100%"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.1.3' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-09-05','Dépense','Communication',3000, sl.id, ba.id, '{"n_piece": "PC0004", "projet": "Projet A", "code": "2.1.4", "commentaire": "Realisation festival ecoles 2024 - solde 100%"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.1.4' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-12-31','Dépense','Salaires',56800, sl.id, ba.id, '{"n_piece": "PC0035", "projet": "Frais generaux", "code": "1.1", "commentaire": "Annee complete 2024"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.1' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-12-31','Dépense','Bureaux',6000, sl.id, ba.id, '{"n_piece": "PC0038", "projet": "Frais generaux", "code": "1.2", "commentaire": "Annee complete 2024"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.2' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2024-12-31','Dépense','Frais administratifs',2800, sl.id, ba.id, '{"n_piece": "PC0041", "projet": "Frais generaux", "code": "1.3", "commentaire": "Annee complete 2024"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.3' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Formateurs terrain',4050, sl.id, ba.id, '{"n_piece": "PC0005", "projet": "Projet B", "code": "2.2.1", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.1' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Formateurs terrain',4050, sl.id, ba.id, '{"n_piece": "PC0006", "projet": "Projet B", "code": "2.2.1", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.1' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Deplacements / missions',2700, sl.id, ba.id, '{"n_piece": "PC0009", "projet": "Projet B", "code": "2.2.2", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.2' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Deplacements / missions',2700, sl.id, ba.id, '{"n_piece": "PC0010", "projet": "Projet B", "code": "2.2.2", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.2' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Materiel pedagogique',1800, sl.id, ba.id, '{"n_piece": "PC0013", "projet": "Projet B", "code": "2.2.3", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.3' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Materiel pedagogique',1800, sl.id, ba.id, '{"n_piece": "PC0014", "projet": "Projet B", "code": "2.2.3", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.3' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Location de salles',1575, sl.id, ba.id, '{"n_piece": "PC0017", "projet": "Projet B", "code": "2.2.4", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.4' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Location de salles',1575, sl.id, ba.id, '{"n_piece": "PC0018", "projet": "Projet B", "code": "2.2.4", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.4' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Suivi-evaluation',1125, sl.id, ba.id, '{"n_piece": "PC0021", "projet": "Projet B", "code": "2.2.5", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.5' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-06-30','Dépense','Suivi-evaluation',1125, sl.id, ba.id, '{"n_piece": "PC0022", "projet": "Projet B", "code": "2.2.5", "commentaire": "Realisation 2025 - 90% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.5' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-12-31','Dépense','Salaires',56800, sl.id, ba.id, '{"n_piece": "PC0036", "projet": "Frais generaux", "code": "1.1", "commentaire": "Annee complete 2025"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.1' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-12-31','Dépense','Bureaux',6000, sl.id, ba.id, '{"n_piece": "PC0039", "projet": "Frais generaux", "code": "1.2", "commentaire": "Annee complete 2025"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.2' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2025-12-31','Dépense','Frais administratifs',2800, sl.id, ba.id, '{"n_piece": "PC0042", "projet": "Frais generaux", "code": "1.3", "commentaire": "Annee complete 2025"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.3' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Formateurs terrain',1800, sl.id, ba.id, '{"n_piece": "PC0007", "projet": "Projet B", "code": "2.2.1", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.1' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Formateurs terrain',1800, sl.id, ba.id, '{"n_piece": "PC0008", "projet": "Projet B", "code": "2.2.1", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.1' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Deplacements / missions',1200, sl.id, ba.id, '{"n_piece": "PC0011", "projet": "Projet B", "code": "2.2.2", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.2' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Deplacements / missions',1200, sl.id, ba.id, '{"n_piece": "PC0012", "projet": "Projet B", "code": "2.2.2", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.2' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Materiel pedagogique',800, sl.id, ba.id, '{"n_piece": "PC0015", "projet": "Projet B", "code": "2.2.3", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.3' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Materiel pedagogique',800, sl.id, ba.id, '{"n_piece": "PC0016", "projet": "Projet B", "code": "2.2.3", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.3' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Location de salles',700, sl.id, ba.id, '{"n_piece": "PC0019", "projet": "Projet B", "code": "2.2.4", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.4' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Location de salles',700, sl.id, ba.id, '{"n_piece": "PC0020", "projet": "Projet B", "code": "2.2.4", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.4' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Suivi-evaluation',500, sl.id, ba.id, '{"n_piece": "PC0023", "projet": "Projet B", "code": "2.2.5", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.5' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-05-31','Dépense','Suivi-evaluation',500, sl.id, ba.id, '{"n_piece": "PC0024", "projet": "Projet B", "code": "2.2.5", "commentaire": "Realisation 2026 (a fin juillet) - 40% alloc. annuelle (part fonds propres)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.2.5' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Developpement plateforme MOOC',12000, sl.id, ba.id, '{"n_piece": "PC0025", "projet": "Projet C", "code": "2.3.1", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.1' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Developpement plateforme MOOC',12000, sl.id, ba.id, '{"n_piece": "PC0026", "projet": "Projet C", "code": "2.3.1", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part BAD)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.1' and ba.code='BAD';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Production de contenus (video/cours)',13500, sl.id, ba.id, '{"n_piece": "PC0027", "projet": "Projet C", "code": "2.3.2", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.2' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Production de contenus (video/cours)',13500, sl.id, ba.id, '{"n_piece": "PC0028", "projet": "Projet C", "code": "2.3.2", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part BAD)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.2' and ba.code='BAD';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Hebergement / technique',3000, sl.id, ba.id, '{"n_piece": "PC0029", "projet": "Projet C", "code": "2.3.3", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.3' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Hebergement / technique',3000, sl.id, ba.id, '{"n_piece": "PC0030", "projet": "Projet C", "code": "2.3.3", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part BAD)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.3' and ba.code='BAD';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Communication / diffusion',4500, sl.id, ba.id, '{"n_piece": "PC0031", "projet": "Projet C", "code": "2.3.4", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.4' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Communication / diffusion',4500, sl.id, ba.id, '{"n_piece": "PC0032", "projet": "Projet C", "code": "2.3.4", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part BAD)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.4' and ba.code='BAD';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Coordination pedagogique',3000, sl.id, ba.id, '{"n_piece": "PC0033", "projet": "Projet C", "code": "2.3.5", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part UE)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.5' and ba.code='UE';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-15','Dépense','Coordination pedagogique',3000, sl.id, ba.id, '{"n_piece": "PC0034", "projet": "Projet C", "code": "2.3.5", "commentaire": "Realisation 2026 (a fin juillet) - 60% du budget (part BAD)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='2.3.5' and ba.code='BAD';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-30','Dépense','Salaires',31240, sl.id, ba.id, '{"n_piece": "PC0037", "projet": "Frais generaux", "code": "1.1", "commentaire": "Janvier a juin 2026 (partiel)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.1' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-30','Dépense','Bureaux',3300, sl.id, ba.id, '{"n_piece": "PC0040", "projet": "Frais generaux", "code": "1.2", "commentaire": "Janvier a juin 2026 (partiel)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.2' and ba.code='FP';
insert into gl_entries (entry_date, entry_type, label, amount, line_id, bailleur_id, raw, source) select '2026-06-30','Dépense','Frais administratifs',1540, sl.id, ba.id, '{"n_piece": "PC0043", "projet": "Frais generaux", "code": "1.3", "commentaire": "Janvier a juin 2026 (partiel)"}'::jsonb, 'csv' from structure_lines sl, bailleurs ba where sl.code='1.3' and ba.code='FP';

commit;